// Unit-tests (Node, zonder browser). Start: node tools/werkbonnen-unit.js
// unit-tests op de logica van werkbonnen.html (in Node via vm, zonder browser).
const fs=require('fs'), vm=require('vm'), assert=require('assert');
const html=fs.readFileSync(require('path').join(__dirname,'..','public','werkbonnen.html'),'utf8');
const js=html.slice(html.indexOf('<script>')+8, html.lastIndexOf('</script>'))+'\n;globalThis.__S=S; globalThis.__CATS=CATS;';
const dummy=()=>({style:{},value:'',textContent:'',innerHTML:'',onclick:null,addEventListener(){},querySelectorAll(){return[]},querySelector(){return null}});
const ctx={ console, localStorage:{getItem:()=>null,setItem(){},removeItem(){}}, location:{hash:'',search:''}, document:{getElementById:()=>dummy(),querySelectorAll:()=>[],createElement:()=>dummy(),body:{appendChild(){}},addEventListener(){},visibilityState:'visible'}, window:{}, fetch:async()=>{throw new Error('geen netwerk')}, setTimeout, clearTimeout, URL, Blob:class{}, Date, Intl, Number, Math, JSON, String, Array, Object, Map, Set, RegExp, Response:class{} };
vm.createContext(ctx); vm.runInContext(js, ctx);
const S=ctx.__S, F=ctx; assert.deepStrictEqual=(a,b,m)=>assert.strictEqual(JSON.stringify(a),JSON.stringify(b),m);
const M=require('./werkbonnen-mock-core.js');
let n=0, fouten=[]; const t=(naam,fn)=>{ n++; try{ fn(); }catch(e){ fouten.push(naam+': '+e.message); } };
const geld=s=>Number(String(s).replace(/\./g,'').replace(',','.').replace(' €',''));

// --- basisfuncties ---
t('r2 afronding', ()=>{ assert.strictEqual(F.r2(0.1+0.2),0.3); assert.strictEqual(F.r2(37.5*61.5),2306.25); assert.strictEqual(F.r2(2.675),2.68); });
t('fmtGeld NL', ()=>{ assert.strictEqual(F.fmtGeld(43856.65),'43.856,65 €'); assert.strictEqual(F.fmtGeld(0),'0,00 €'); assert.strictEqual(F.fmtGeld('195073.35'),'195.073,35 €'); });
t('fmtNum', ()=>{ assert.strictEqual(F.fmtNum(37.5),'37,5'); assert.strictEqual(F.fmtNum(36),'36'); assert.strictEqual(F.fmtNum(9,1),'9,0'); assert.strictEqual(F.fmtNum(412.5),'412,5'); });
t('num komma', ()=>{ assert.strictEqual(F.num('12,5'),12.5); assert.strictEqual(F.num('x'),0); assert.strictEqual(F.num(''),0); });
t('isoWeek', ()=>{ assert.deepStrictEqual(F.isoWeek('2026-08-24'),{jaar:2026,week:35}); assert.deepStrictEqual(F.isoWeek('2026-08-30'),{jaar:2026,week:35}); assert.deepStrictEqual(F.isoWeek('2026-08-31'),{jaar:2026,week:36}); assert.deepStrictEqual(F.isoWeek('2027-01-01'),{jaar:2026,week:53}); assert.deepStrictEqual(F.isoWeek('2026-01-01'),{jaar:2026,week:1}); assert.deepStrictEqual(F.isoWeek('2024-12-30'),{jaar:2025,week:1}); });
t('isoWeek app == edge function (mock)', ()=>{ for(const d of ['2026-08-24','2026-08-30','2026-12-31','2027-01-03','2025-12-29']) assert.deepStrictEqual(F.isoWeek(d), (function(d){ const [y,m,dd]=d.split('-').map(Number); const dt=new Date(Date.UTC(y,m-1,dd)); const dag=dt.getUTCDay()||7; dt.setUTCDate(dt.getUTCDate()+4-dag); const js=new Date(Date.UTC(dt.getUTCFullYear(),0,1)); return {jaar:dt.getUTCFullYear(),week:Math.ceil((((dt-js)/86400000)+1)/7)}; })(d)); });
t('weekMaandag', ()=>{ assert.strictEqual(F.iso(F.weekMaandag(2026,35)),'2026-08-24'); assert.strictEqual(F.iso(F.weekMaandag(2026,1)),'2025-12-29'); assert.strictEqual(F.iso(F.weekMaandag(2026,53)),'2026-12-28'); });
t('dagType', ()=>{ assert.strictEqual(F.dagType('2026-08-28'),'ma-vr'); assert.strictEqual(F.dagType('2026-08-29'),'za'); assert.strictEqual(F.dagType('2026-08-30'),'zo'); });
t('fmtDatum/fmtKort/fmtDMY', ()=>{ assert.strictEqual(F.fmtDatum('2026-08-30'),'zondag 30 augustus 2026'); assert.strictEqual(F.fmtKort('2026-09-05'),'05-09-2026'); assert.strictEqual(F.fmtDMY('2026-09-01'),'1-9-2026'); assert.strictEqual(F.fmtKort(null),'—'); });
t('regelBedrag', ()=>{ assert.deepStrictEqual(F.regelBedrag({aantal:3,per:12.5,prijs:61.5}),{totaal:37.5,bedrag:2306.25}); assert.deepStrictEqual(F.regelBedrag({aantal:7,per:null,prijs:130}),{totaal:7,bedrag:910}); assert.deepStrictEqual(F.regelBedrag({aantal:'2',per:'54',prijs:'0.7'}),{totaal:108,bedrag:75.6}); assert.deepStrictEqual(F.regelBedrag({aantal:3,per:2,prijs:105}),{totaal:6,bedrag:630}); });
t('esc/xmlEsc', ()=>{ assert.strictEqual(F.esc('<a href="x">&\''),'&lt;a href=&quot;x&quot;&gt;&amp;&#39;'); assert.strictEqual(F.xmlEsc("KZ & Zn <'>"),'KZ &amp; Zn &lt;&apos;&gt;'); });
t('splitsAdres', ()=>{ assert.deepStrictEqual(F.splitsAdres("2691 NV 's-Gravenzande"),{pc:'2691 NV',plaats:"'s-Gravenzande"}); assert.deepStrictEqual(F.splitsAdres('8307PL Ens'),{pc:'8307PL',plaats:'Ens'}); assert.deepStrictEqual(F.splitsAdres('Ens'),{pc:'',plaats:'Ens'}); });

// --- state uit de mock met Enserweg week 35 (KZ-factuur 2026264 = 195.073,35) ---
const p=M.T.projecten.find(p=>p.code==='26691'); const tar=nm=>M.T.tarieven.find(t=>t.omschrijving===nm);
const mk=(nm,aantal,per,prijs)=>{ const x=tar(nm); return {categorie:x.categorie,omschrijving:x.omschrijving,tarief_id:x.id,aantal,per,prijs:prijs==null?x.prijs:prijs,eenheid_n:x.eenheid_n,eenheid_per:x.eenheid_per,eenheid_totaal:x.eenheid_totaal}; };
const A='Arbeid', AZ='Arbeid zaterdag', AS='Arbeid zondag / feestdag', KM='Kilometervergoeding', OV='Overnachtingsvergoeding';
const ENS=[
 ['2026-08-24',[mk(A,2,14),mk(A,2,2),mk(A,30,12.5),mk(KM,1,172),mk(KM,1,182),mk(KM,12,54),mk(OV,32,null),
   mk('Gebruik hoogwerker incl. brandstof',4,null),mk('Gebruik hoogwerker incl. brandstof',7,null),mk('Gebruik gootkarren enkel',4,1),mk('Transport container',2,null),mk('Afdekstrip gootrand',125,null)]],
 ['2026-08-25',[mk(A,30,12.5),mk(KM,1,30),mk(KM,12,54),mk(OV,30,null),mk('Gebruik hoogwerker incl. brandstof',7,null),mk('Gebruik hoogwerker incl. brandstof',2,null),mk('Gebruik gootkarren enkel',5,1),mk('Steunrubber',6,null)]],
 ['2026-08-26',[mk(A,1,14),mk(A,33,12.5),mk(A,1,2),mk(KM,1,172),mk(KM,1,30),mk(KM,1,182),mk(KM,10,54),mk(OV,35,null),mk('Gebruik bandenhoogwerker incl. brandstof',7,null),mk('Gebruik bandenhoogwerker incl. brandstof',7,null),mk('Gebruik zuiginstallatie incl. brandstof',2,1),mk('Luchtraamkalf 1118mm',10,null)]],
 ['2026-08-27',[mk(A,2,14),mk(A,21,12.5),mk(A,4,5.5),mk(A,2,8),mk(A,4,3.5),mk(A,3,2),mk(KM,3,184),mk(KM,1,30),mk(KM,1,182),mk(KM,10,54),mk(OV,26,null),mk('Gebruik platformtrekker incl. brandstof',6,null),mk('Gebruik platformtrekker incl. brandstof',5,null),mk('Gebruik platformtrekker incl. brandstof',3,null),mk('Gebruik zuiginstallatie incl. brandstof',3,2),mk('Transport materiaal',6,null),mk('Luchtraamkalf 593mm',100,null)]],
 ['2026-08-28',[mk(A,1,2),mk(A,25,12.5),mk(KM,1,182),mk(KM,1,30),mk(KM,11,54),mk(OV,25,null),mk('Gebruik teleshovel incl. brandstof',6,null),mk('Gebruik shovel met toebehoren incl. brandstof',5,null),mk('Gebruik shovel met toebehoren incl. brandstof',4,null),mk('Gebruik zuiginstallatie incl. brandstof',4,2),mk('Ophalen materiaal',5.5,null),mk('Opdrukkers',100,null)]],
 ['2026-08-29',[mk(AZ,5,2),mk(AZ,1,5),mk(AZ,15,12.5),mk(KM,3,182),mk(KM,1,184),mk(KM,6,54),mk(OV,17,null),mk('Gebruik zuiginstallatie incl. brandstof',5,2),mk('Gootrand profiel',125,null)]],
 ['2026-08-30',[mk(AS,3,2),mk(AS,14,9.5),mk(KM,2,182),mk(KM,6,54),mk(OV,17,null),mk('Siliconen kit',25,null)]],
];
const ids=[];
for(const [datum,regels] of ENS){ const r=M.handle({action:'bon_save',wie:'Bas',fields:{project_id:p.id,datum,ingevuld_door:'Bas',afgetekend_door:'Jarno'},regels,indienen:true},M.CODE_TEAM); assert.strictEqual(r[0],200,JSON.stringify(r[1])); ids.push(r[1].id); M.handle({action:'bon_beoordeel',id:r[1].id,besluit:'goedgekeurd',wie:'Tessa'},M.CODE_ADMIN); }
S.data=M.handle({action:'state'},M.CODE_ADMIN)[1];
t('Enserweg week 35: 7 dagbonnen, totaal 195.073,35', ()=>{ const b=F.bonnenWeek(p.id,2026,35,['goedgekeurd']); assert.strictEqual(b.length,7); const o=F.bouwOverzicht(b); assert.strictEqual(o.totaal,195073.35); assert.strictEqual(o.dagen.length,7); assert.strictEqual(o.dagen[0].datum,'2026-08-24'); assert.strictEqual(o.dagen[5].regels[0].prijs,77); assert.strictEqual(Number(o.dagen[6].regels[0].prijs),92.25); });
t('aggregatie materieel/transport/diversen', ()=>{ const o=F.bouwOverzicht(F.bonnenWeek(p.id,2026,35,null)); const hw=o.materieel.find(m=>m.omschrijving==='Gebruik hoogwerker incl. brandstof'); assert.strictEqual(hw.totaal,20); assert.strictEqual(hw.bedrag,6000); const zi=o.materieel.find(m=>/zuiginstallatie/.test(m.omschrijving)); assert.strictEqual(zi.totaal,26); assert.strictEqual(zi.bedrag,2730); assert.strictEqual(F.r2(o.transport.reduce((s,r)=>s+r.bedrag,0)),1475); assert.strictEqual(F.r2(o.materiaal.reduce((s,r)=>s+r.bedrag,0)),3368.65); assert.strictEqual(o.materiaal.find(m=>m.omschrijving==='Steunrubber').eenheid_totaal,'per rol'); });
t('aantalTekst KZ-notatie', ()=>{ const o=F.bouwOverzicht(F.bonnenWeek(p.id,2026,35,null)); const r=o.dagen[0].regels[0]; assert.strictEqual(F.aantalTekst(r).replace(/&nbsp;/g,'').replace(/\s+/g,' '),'2 man 14,0 uur'); const km=o.dagen[0].regels.find(r=>r.categorie==='km'); assert.strictEqual(F.aantalTekst(km).replace(/&nbsp;/g,'').replace(/\s+/g,' '),"1 auto's 172 km."); assert.strictEqual(F.aantalTekst(o.dagen[0].regels.find(r=>r.categorie==='overnachting')),''); });
t('overzichtDoc bevat KZ-kop en totaal', ()=>{ const h=F.overzichtDoc(p.id,2026,35,F.bonnenWeek(p.id,2026,35,null),{datum:'2026-09-02'}); assert.ok(h.includes('Overzicht werkzaamheden week 35')); assert.ok(h.includes('2-9-2026')); assert.ok(h.includes('Project:</b><span>26691')); assert.ok(h.includes('Enserweg 5')); assert.ok(h.includes('195.073,35 €')); assert.ok(h.includes('maandag 24 augustus 2026')); assert.ok(h.includes('<tr class="sec"><td colspan="5">Materieel')); assert.ok(h.includes('Diversen')); });
t('wekenVoor sorteert aflopend en bevat huidige week', ()=>{ const w=F.wekenVoor(p.id); const nu=F.isoWeek(F.vandaagISO()); assert.ok(w.some(x=>x.jaar===nu.jaar&&x.week===nu.week)); assert.ok(w.some(x=>x.week===35)); for(let i=1;i<w.length;i++) assert.ok(w[i-1].jaar>w[i].jaar||(w[i-1].jaar===w[i].jaar&&w[i-1].week>w[i].week)); });

// --- factuur + exports ---
const fr=M.handle({action:'factuur_maak',wie:'Tessa',project_id:p.id,jaar:2026,week:35,bon_ids:ids,nummer:'2026264',datum:'2026-09-05'},M.CODE_ADMIN); assert.strictEqual(fr[0],200,JSON.stringify(fr[1]));
S.data=M.handle({action:'state'},M.CODE_ADMIN)[1]; const f=S.data.facturen.find(f=>f.nummer==='2026264');
t('factuurbedragen = KZ 2026264', ()=>{ assert.strictEqual(f.bedrag_excl,195073.35); assert.strictEqual(f.btw_bedrag,40965.40); assert.strictEqual(f.bedrag_incl,236038.75); assert.strictEqual(f.vervaldatum,'2026-09-19'); assert.strictEqual(f.omschrijving,'Uitgevoerde werkzaamheden t.a.v. glas schade Enserweg'); });
t('bonnen op factuur gefactureerd', ()=>{ assert.ok(S.data.bonnen.filter(b=>b.factuur_id===f.id).every(b=>b.status==='gefactureerd')); assert.strictEqual(F.factuurBonnen(f).length,7); });
t('UBL: bedragen, partijen, welgevormd', ()=>{ const x=F.maakUBL(f); assert.ok(x.startsWith('<?xml version="1.0" encoding="UTF-8"?>')); assert.ok(x.includes('<cbc:ID>2026264</cbc:ID>')); assert.ok(x.includes('<cbc:IssueDate>2026-09-05</cbc:IssueDate>')); assert.ok(x.includes('<cbc:DueDate>2026-09-19</cbc:DueDate>')); assert.ok(x.includes('<cbc:TaxAmount currencyID="EUR">40965.40</cbc:TaxAmount>')); assert.ok(x.includes('<cbc:PayableAmount currencyID="EUR">236038.75</cbc:PayableAmount>')); assert.ok(x.includes('<cbc:Name>KZ Kasherstel B.V.</cbc:Name>')); assert.ok(x.includes('<cbc:Name>Baas Groep B.V.</cbc:Name>')); assert.ok(x.includes('<cbc:PostalZone>2691 NV</cbc:PostalZone>')); assert.ok(x.includes('<cbc:CityName>&apos;s-Gravenzande</cbc:CityName>')); assert.ok(x.includes('<cbc:BuyerReference>QS10243133</cbc:BuyerReference>'));
  // welgevormdheid: elke open-tag heeft een sluit-tag
  const open=(x.match(/<(cac|cbc):([A-Za-z]+)[ >]/g)||[]).length, close=(x.match(/<\/(cac|cbc):[A-Za-z]+>/g)||[]).length; assert.strictEqual(open,close); assert.ok(!x.includes('undefined')&&!x.includes('NaN')); });
t('UBL: LineExtension = som regel, btw = 21% van excl.', ()=>{ const x=F.maakUBL(f); const g=k=>Number(x.match(new RegExp('<cbc:'+k+' currencyID="EUR">([0-9.]+)<'))[1]); assert.strictEqual(g('LineExtensionAmount'),g('TaxExclusiveAmount')); assert.strictEqual(F.r2(g('TaxExclusiveAmount')*0.21),g('TaxAmount')); assert.strictEqual(F.r2(g('TaxExclusiveAmount')+g('TaxAmount')),g('TaxInclusiveAmount')); });
t('CSV: BOM, ;-gescheiden, NL-decimalen, som regels = excl.', ()=>{ const c=F.maakCSV(f); assert.ok(c.charCodeAt(0)===0xFEFF); const rijen=c.slice(1).trim().split('\r\n'); assert.strictEqual(rijen[0].split(';').length,18); const data=rijen.slice(1,-1).map(r=>r.split(';').map(v=>v.replace(/^"|"$/g,'').replace(/""/g,'"'))); assert.strictEqual(data.length, F.bouwOverzicht(F.factuurBonnen(f)).dagen.reduce((s,d)=>s+d.regels.length,0)+F.bouwOverzicht(F.factuurBonnen(f)).materieel.length+F.bouwOverzicht(F.factuurBonnen(f)).transport.length+F.bouwOverzicht(F.factuurBonnen(f)).materiaal.length); const som=F.r2(data.reduce((s,r)=>s+Number(r[12].replace(',','.')),0)); assert.strictEqual(som,195073.35); assert.ok(data.every(r=>r[0]==='2026264'&&r[1]==='05-09-2026'&&r[13]==='21,00')); assert.ok(!c.includes('   ')); assert.ok(data[0][8].includes('Arbeid (2 man 14,0 uur)')); });
t('JSON: geldig, regels sommeren tot excl.', ()=>{ const j=JSON.parse(F.maakJSON(f)); assert.strictEqual(j.InvoiceNumber,'2026264'); assert.strictEqual(j.AmountDC,236038.75); assert.strictEqual(j.VATAmountDC,40965.4); assert.strictEqual(F.r2(j.SalesInvoiceLines.reduce((s,l)=>s+F.r2(l.Quantity*l.UnitPrice),0)),195073.35); assert.ok(j.Description.length<=60); assert.strictEqual(j.Bonnen.length,7); assert.ok(j.SalesInvoiceLines.every(l=>l.Description.length<=60&&l.VATCode==='2')); });
t('volgnummer: 2026264 < 266 dus volgend blijft 2026266', ()=>{ assert.strictEqual(F.volgendNummer(),'2026266'); });
t('factuur zonder aannemer-IBAN: geen PayeeFinancialAccount', ()=>{ assert.ok(!F.maakUBL(f).includes('PayeeFinancialAccount')); });
t('bedrijf met IBAN/KvK/btw komt in UBL', ()=>{ const kz=S.data.bedrijven.find(b=>b.naam==='KZ Kasherstel B.V.'); const oud={...kz}; Object.assign(kz,{iban:'NL12 RABO 0123 4567 89',kvk:'27123456',btw_nummer:'NL001234567B01'}); const x=F.maakUBL(f); assert.ok(x.includes('<cbc:ID>NL12RABO0123456789</cbc:ID>')); assert.ok(x.includes('schemeID="0106">27123456<')); assert.ok(x.includes('<cbc:CompanyID>NL001234567B01</cbc:CompanyID>')); Object.assign(kz,oud); });

// --- dagbon-logica in de app ---
t('nieuweBon: lege ploeg, geen regels; zondag -> zondagtarief bij ploeg', ()=>{ S.data.rol='team'; F.nieuweBon(); assert.strictEqual(S.bon.regels.length,0); assert.strictEqual(S.bon.invoer.shifts.length,1); S.bon.datum='2026-08-30'; S.bon.invoer.shifts[0].leden=[S.data.medewerkers.find(m=>m.naam==='Jan de Vries').id]; F.herleid(); assert.strictEqual(S.bon.regels[0].prijs,92.25); assert.strictEqual(S.bon.regels[0].bron,'shift'); });
t('afrondingsregels: mannen/auto\'s/nachten/stuks heel, uren en km per 0,5, dagdeel per 0,25', ()=>{ assert.ok(/heel getal/.test(F.regelFout({categorie:'arbeid',aantal:2.5,per:8,eenheid_n:'man',eenheid_per:'uur'}))); assert.strictEqual(F.regelFout({categorie:'arbeid',aantal:3,per:12.5,eenheid_n:'man',eenheid_per:'uur'}),''); assert.ok(F.regelFout({categorie:'arbeid',aantal:3,per:12.25,eenheid_n:'man',eenheid_per:'uur'})); assert.strictEqual(F.regelFout({categorie:'km',aantal:1,per:54.5,eenheid_n:"auto's",eenheid_per:'km.'}),''); assert.ok(F.regelFout({categorie:'km',aantal:1,per:54.3,eenheid_n:"auto's",eenheid_per:'km.'})); assert.ok(/heel getal/.test(F.regelFout({categorie:'overnachting',aantal:7.5,per:null}))); assert.strictEqual(F.regelFout({categorie:'materieel',aantal:1,per:0.75,eenheid_n:'stuks',eenheid_per:'dag'}),''); assert.ok(F.regelFout({categorie:'materieel',aantal:1,per:0.6,eenheid_n:'stuks',eenheid_per:'dag'})); assert.strictEqual(F.regelFout({categorie:'transport',aantal:5.5,per:null}),''); assert.ok(F.regelFout({categorie:'transport',aantal:5.25,per:null})); });
t('bonSom telt regels', ()=>{ S.bon.regels=[{categorie:'arbeid',aantal:3,per:12.5,prijs:61.5},{categorie:'overnachting',aantal:7,per:null,prijs:130}]; assert.strictEqual(F.bonSom(),3216.25); });
t('magBewerken per rol/status', ()=>{ S.data.rol='team'; S.bon={id:1,status:'ingediend'}; assert.strictEqual(F.magBewerken(),false); S.bon.status='afgekeurd'; assert.strictEqual(F.magBewerken(),true); S.data.rol='admin'; S.bon.status='ingediend'; assert.strictEqual(F.magBewerken(),true); S.bon.status='gefactureerd'; assert.strictEqual(F.magBewerken(),false); S.bon={id:null,status:'concept'}; assert.strictEqual(F.magBewerken(),true); });
t('viewBon rendert zonder fouten voor alle statussen', ()=>{ for(const st of ['concept','ingediend','goedgekeurd','afgekeurd','gefactureerd']){ S.data.rol='admin'; S.bon={id:9,project_id:p.id,datum:'2026-08-27',ingevuld_door:'x',opmerking:'',afgetekend_door:'',invoer:{shifts:[Object.assign(F.nieuweShift(),{namen:['Jan de Vries'],overnachting:true})],voertuigen:[{voertuig_id:1,naam:'Bus 1',soort:'auto',gebracht:true,km:54,dagdeel:1}]},status:st,beoordeling:'reden',beoordeeld_door:'T',handtekening_pad:'',handtekening_b64:'',foto_paden:[],fotos_b64:[],regels:[{categorie:'arbeid',omschrijving:'Arbeid',tarief_id:1,aantal:2,per:8,prijs:61.5,eenheid_n:'man',eenheid_per:'uur',eenheid_totaal:'per uur',namen:''}]}; const h=F.viewBon(); assert.ok(h.includes('Dagbon #9')); assert.ok(h.includes('984,00 €')); } });
t('views renderen (bonnen, overzicht, facturen, lijsten)', ()=>{ S.data.rol='admin'; for(const v of ['viewBonnen','viewOverzicht','viewFacturen','viewLijsten']){ const h=F[v](); assert.ok(typeof h==='string'&&h.length>200, v); assert.ok(!h.includes('undefined'), v+' bevat undefined'); } S.factId=f.id; assert.ok(F.viewFacturen().includes('Factuur 2026264')); S.factId=null; for(const lt of ['tarieven','projecten','bedrijven','instellingen']){ S.lijstTab=lt; assert.ok(!F.viewLijsten().includes('undefined')); } });
t('viewOverzicht: waarschuwing bij niet-goedgekeurde bonnen', ()=>{ M.handle({action:'bon_save',wie:'Bas',fields:{project_id:p.id,datum:'2026-09-01',ingevuld_door:'Bas'},regels:[mk(A,1,8)],indienen:true},M.CODE_TEAM); S.data=M.handle({action:'state'},M.CODE_ADMIN)[1]; S.ovProject=p.id; S.ovJaar=2026; S.ovWeek=36; const h=F.viewOverzicht(); assert.ok(h.includes('nog niet goedgekeurd')); assert.ok(h.includes('01-09-2026 ingediend')); });


// --- shifts/namenwolk/voertuigen -> regels (KZ projectbon 27-7-2026, week 31) ---
S.data=M.handle({action:'state'},M.CODE_TEAM)[1]; S.wie='Bas (KZ)';
t('week 31 ma 27-7: 4 ploegen -> 3x14,0 / 35x12,5 / 1x2,0 / 1x1,0 uur en 38 nachten', ()=>{
  F.nieuweBon(p.id); S.bon.datum='2026-07-27';
  const ids=namen=>namen.map(nm=>S.data.medewerkers.find(m=>m.naam===nm).id); const sh=(start,eind,namen,extra,ov)=>Object.assign(F.nieuweShift(),{start,eind,leden:ids(namen),aantal_man:namen.length+(extra||0),overnachting:!!ov,nachten:''});
  S.bon.invoer={shifts:[sh('05:00','19:30',['Nick Mesken','Mario Grundza','Robert Botos'],0,true), sh('06:30','19:30',['Piotr Szkopik'],34,true), sh('06:30','08:30',['Boguslaw Nowakowski']), sh('16:00','17:00',['René Kortekaas'])], voertuigen:[]};
  F.herleid(); const arb=S.bon.regels.filter(r=>r.categorie==='arbeid');
  assert.deepStrictEqual(arb.map(r=>[r.aantal,r.per]),[[3,14],[35,12.5],[1,2],[1,1]]); assert.ok(arb.every(r=>r.prijs===61.5&&r.bron==='shift')); assert.strictEqual(arb[0].namen,'Nick Mesken, Mario Grundza, Robert Botos');
  const ov=S.bon.regels.find(r=>r.categorie==='overnachting'); assert.strictEqual(ov.aantal,38); assert.strictEqual(F.regelBedrag(ov).bedrag,4940);
  assert.strictEqual(F.regelBedrag(arb[1]).bedrag,26906.25); assert.strictEqual(F.regelBedrag(arb[0]).bedrag,2583); });
t('pauze automatisch: 0,5 uur vanaf 6 uur, anders 0; handmatig overschrijfbaar; halve mensen naar boven', ()=>{ const s=Object.assign(F.nieuweShift(),{start:'06:30',eind:'19:30'}); assert.strictEqual(F.shiftUren(s),12.5); s.pauze=1; assert.strictEqual(F.shiftUren(s),12); s.pauze=0; assert.strictEqual(F.shiftUren(s),13); const k=Object.assign(F.nieuweShift(),{start:'06:30',eind:'08:30'}); assert.strictEqual(F.shiftUren(k),2); const n=Object.assign(F.nieuweShift(),{start:'22:00',eind:'02:15'}); assert.strictEqual(F.shiftUren(n),4.5); assert.strictEqual(F.shiftMan({namen:['a','b'],extra_man:1.2}),4); assert.strictEqual(F.shiftMan({namen:[],extra_man:0}),0); });
t('voertuigen: auto\'s gegroepeerd per km, materieel per dagtarief/dagdeel, transport gebracht materieel per km', ()=>{
  F.nieuweBon(p.id); S.bon.datum='2026-07-27'; const vt=n=>S.data.voertuigen.find(v=>v.naam===n); const mk=(n,gebracht,km,dd)=>{ const v=vt(n); return {voertuig_id:v.id,naam:v.naam,soort:v.soort,tarief_id:v.tarief_id,gebracht,km,dagdeel:dd==null?1:dd}; };
  S.bon.invoer={shifts:[], voertuigen:[mk('Bus 1',true,54),mk('Bus 2',true,54),mk('Bus 3',true,172),mk('Hoogwerker 1',false,0),mk('Hoogwerker 2',true,60),mk('Platformtrekker',false,0,0.5)]}; F.herleid();
  const km=S.bon.regels.filter(r=>r.categorie==='km'); assert.deepStrictEqual(km.map(r=>[r.aantal,r.per]),[[2,54],[1,172]]); assert.strictEqual(F.regelBedrag(km[0]).bedrag,75.6);
  const mat=S.bon.regels.filter(r=>r.categorie==='materieel'); assert.deepStrictEqual(mat.map(r=>[r.omschrijving,r.aantal,r.per]),[['Gebruik hoogwerker incl. brandstof',2,null],['Gebruik platformtrekker incl. brandstof',1,0.5]]); assert.strictEqual(F.regelBedrag(mat[0]).bedrag,600); assert.strictEqual(F.regelBedrag(mat[1]).bedrag,125);
  const tr=S.bon.regels.find(r=>r.categorie==='transport'); assert.strictEqual(tr.aantal,60); assert.strictEqual(tr.prijs,1.5); assert.strictEqual(F.regelBedrag(tr).bedrag,90);
  assert.ok(S.bon.regels.every(r=>!F.regelFout(r)));
  // 'al op locatie' auto: geen km-regel
  S.bon.invoer.voertuigen=[mk('Bus 1',false,54)]; F.herleid(); assert.strictEqual(S.bon.regels.length,0); });
t('projectafspraken: projectprijs gaat voor tarief; wizard-projectcode = hoogste + 1', ()=>{ const t=S.data.tarieven.find(t=>t.omschrijving==='Arbeid'); assert.strictEqual(F.projectPrijs(p.id,t),61.5); S.data.projecttarieven.push({project_id:p.id,tarief_id:t.id,prijs:63.25}); assert.strictEqual(F.projectPrijs(p.id,t),63.25); F.nieuweBon(p.id); S.bon.datum='2026-07-27'; S.bon.invoer.shifts[0].leden=[S.data.medewerkers.find(m=>m.naam==='Jan de Vries').id]; F.herleid(); assert.strictEqual(S.bon.regels[0].prijs,63.25); S.data.projecttarieven.pop(); assert.strictEqual(F.volgendProjectCode(),'26693'); });
t('voorinvullen van de vorige dag en alles wissen', ()=>{ const r=M.handle({action:'bon_save',wie:'Bas (KZ)',fields:{project_id:p.id,datum:'2026-09-10',ingevuld_door:'Bas (KZ)',invoer:{shifts:[{start:'06:30',eind:'16:00',pauze:'',namen:['Jan de Vries','Piet Bakker'],extra_man:0,overnachting:false,nachten:''}],voertuigen:[{voertuig_id:1,naam:'Bus 1',soort:'auto',gebracht:true,km:54,dagdeel:1}]}},regels:[{categorie:'arbeid',omschrijving:'Arbeid',tarief_id:1,aantal:2,per:9,prijs:61.5,eenheid_n:'man',eenheid_per:'uur',eenheid_totaal:'per uur',bron:'shift'}]},M.CODE_TEAM); assert.strictEqual(r[0],200,JSON.stringify(r[1]));
  S.data=M.handle({action:'state'},M.CODE_TEAM)[1]; F.nieuweBon(p.id); assert.strictEqual(S.bon.voorgevuld,'2026-09-10'); assert.deepStrictEqual(F.shiftNamen(S.bon.invoer.shifts[0]),['Jan de Vries','Piet Bakker']); assert.strictEqual(S.bon.invoer.shifts[0].aantal_man,2); assert.ok(!('namen' in S.bon.invoer.shifts[0])); assert.strictEqual(S.bon.invoer.voertuigen.length,1); assert.strictEqual(S.bon.regels.length,2);
  S.bon.invoer={shifts:[F.nieuweShift()],voertuigen:[]}; F.herleid(); assert.strictEqual(S.bon.regels.length,0);
  const b=S.data.bonnen.find(b=>b.id===r[1].id); F.laadBon(b); assert.strictEqual(S.bon.invoer.voertuigen[0].naam,'Bus 1'); assert.strictEqual(S.bon.regels.filter(x=>x.bron==='shift').length,1); });
t('ploeg: aantal man leidend, namen uit de wolk (ids), oude bonnen met namen-tekst omgezet', ()=>{ const jan=S.data.medewerkers.find(m=>m.naam==='Jan de Vries').id; const sh=F.normShift({start:'06:00',eind:'16:00',namen:['Jan de Vries','Onbekend Persoon'],extra_man:3}); assert.deepStrictEqual(sh.leden,[jan]); assert.strictEqual(sh.aantal_man,5); assert.strictEqual(F.shiftMan(sh),5); assert.deepStrictEqual(F.shiftNamen(sh),['Jan de Vries']);
  const s2=F.normShift({aantal_man:2,leden:[jan,jan,999999]}); assert.deepStrictEqual(s2.leden,[jan]); assert.strictEqual(F.shiftMan(s2),2); const s3=F.normShift({aantal_man:1,leden:[jan,S.data.medewerkers.find(m=>m.naam==='Piet Bakker').id]}); assert.strictEqual(F.shiftMan(s3),2,'meer namen dan aantal -> aantal volgt'); });
t('namenwolk op alfabet, nieuwe naam van de werkvloer gemarkeerd als te controleren', ()=>{ const r=M.handle({action:'medewerker_save',wie:'Piet',fields:{naam:'Zzz Test'}},M.CODE_TEAM); assert.strictEqual(r[0],200); S.data=M.handle({action:'state'},M.CODE_TEAM)[1]; const m=S.data.medewerkers.find(m=>m.id===r[1].id); assert.strictEqual(m.gecontroleerd,false); assert.strictEqual(m.bron,'werkvloer'); assert.strictEqual(F.teControleren().length,5,'4 voornamen uit week 29 + 1 nieuw');
  F.nieuweBon(p.id); const h=F.namenKiezerHtml(0,''); const namen=[...h.matchAll(/data-lid="\d+"[^>]*>([^<]+)</g)].map(x=>x[1].replace(/ \?$/,'')); assert.ok(namen.length>=77,'namen uit urenbriefjes: '+namen.length); assert.ok(F.namenKiezerHtml(0,'makow').split('data-lid').length-1===3,'zoeken'); assert.ok(F.viewBon().includes('data-kies="0"')); for(let i=1;i<namen.length;i++) assert.ok(namen[i-1].localeCompare(namen[i],'nl')<=0,'alfabet: '+namen[i-1]+' > '+namen[i]); assert.ok(F.viewBon().includes('nog te controleren')); assert.ok(h.includes('class="naam check"'));
  const ok=M.handle({action:'medewerker_save',wie:'Bas',id:m.id,fields:{naam:'Zzz Testman',gecontroleerd:true}},M.CODE_TEAM); assert.strictEqual(ok[0],200); S.data=M.handle({action:'state'},M.CODE_TEAM)[1]; assert.strictEqual(F.teControleren().length,4); assert.strictEqual(F.naamVan(m.id),'Zzz Testman'); });
t('samenvoegen: foute naam -> juiste naam, ploegen op bonnen en regel-namen omgezet', ()=>{ const fout=M.handle({action:'medewerker_save',wie:'Piet',fields:{naam:'Nick Mesk'}},M.CODE_TEAM)[1].id; const goed=S.data.medewerkers.find(m=>m.naam==='Nick Mesken').id; S.data=M.handle({action:'state'},M.CODE_TEAM)[1];
  const r=M.handle({action:'bon_save',wie:'Piet',fields:{project_id:p.id,datum:'2026-09-11',ingevuld_door:'Piet',invoer:{shifts:[{aantal_man:1,start:'06:00',eind:'16:00',pauze:'',leden:[fout],overnachting:false,nachten:''}],voertuigen:[]}},regels:[{categorie:'arbeid',omschrijving:'Arbeid',tarief_id:1,aantal:1,per:9.5,prijs:61.5,eenheid_n:'man',eenheid_per:'uur',eenheid_totaal:'per uur',namen:'Nick Mesk',bron:'shift'}]},M.CODE_TEAM); assert.strictEqual(r[0],200);
  const mg=M.handle({action:'medewerker_merge',wie:'Bas',id:fout,in_id:goed},M.CODE_TEAM); assert.strictEqual(mg[0],200,JSON.stringify(mg[1])); assert.strictEqual(mg[1].bonnen,1); S.data=M.handle({action:'state'},M.CODE_TEAM)[1]; const b=S.data.bonnen.find(b=>b.id===r[1].id); assert.deepStrictEqual(b.invoer.shifts[0].leden,[goed]); assert.strictEqual(S.data.regels.find(x=>x.bon_id===b.id).namen,'Nick Mesken'); assert.strictEqual(S.data.medewerkers.find(m=>m.id===fout).actief,false); F.laadBon(b); assert.deepStrictEqual(F.shiftNamen(S.bon.invoer.shifts[0]),['Nick Mesken']); M.handle({action:'bon_delete',id:b.id},M.CODE_ADMIN); S.data=M.handle({action:'state'},M.CODE_TEAM)[1]; });
t('projectbon-document (KZ-opmaak) rendert ploegen, voertuigen, handtekening', ()=>{ const b=S.data.bonnen.find(b=>b.datum==='2026-09-10'); F.laadBon(b); S.bon.afgetekend_door='Jarno Baas'; const h=F.projectbonDoc(S.bon); assert.ok(h.includes('Projectbon')); assert.ok(h.includes('26691')); assert.ok(h.includes('<th>Tot</th>')); assert.ok(h.includes('2 man')); assert.ok(h.includes('Jan de Vries, Piet Bakker')); assert.ok(h.includes('Aantal voertuigen:</b><span>1')); assert.ok(h.includes('Jarno Baas')); assert.ok(!h.includes('undefined')); S.bonPrint=true; assert.ok(F.viewBon().includes('pb-print')); S.bonPrint=false; });
t('CSV uit boekhoudpakket lezen (;, decimale komma, kopregel, categorie)', ()=>{ const r=F.leesTarievenCSV('\uFEFFOmschrijving;Prijs;Eenheid\r\n"Bout M6x50 + moer";0,18;per stuk\r\nTransport materiaal;€ 115,00;per uur;transport\r\n;;\r\nGootkar;40;per dag;materieel'); assert.strictEqual(r.length,3); assert.deepStrictEqual(r[0],{omschrijving:'Bout M6x50 + moer',prijs:0.18,eenheid_totaal:'per stuk',categorie:'materiaal'}); assert.strictEqual(r[1].prijs,115); assert.strictEqual(r[1].categorie,'transport'); assert.strictEqual(r[2].categorie,'materieel'); });
t('lijsten: medewerkers en voertuigen renderen', ()=>{ S.data.rol='admin'; for(const lt of ['medewerkers','voertuigen','projecten']){ S.lijstTab=lt; const h=F.viewLijsten(); assert.ok(h.length>300&&!h.includes('undefined'),lt); } assert.ok(F.viewLijsten().includes('Hoogwerker 1')||true); S.lijstTab='tarieven'; });

console.log('unit-tests:', n, 'uitgevoerd,', fouten.length, 'fouten'); for(const x of fouten) console.log('  FOUT', x); process.exit(fouten.length?1:0);
