// API-tests via HTTP tegen de mock. Start: node tools/werkbonnen-api.js
// API-tests via HTTP tegen de mock (zelfde regels als de edge function), zonder browser.
 const assert=require('assert');
const { spawn } = require('child_process');
const PORT=18000+Math.floor(Math.random()*2000);
const srv=spawn(process.execPath,[require('path').join(__dirname,'werkbonnen-mock.js')],{stdio:'ignore',env:{...process.env,WB_PORT:String(PORT)}}); process.on('exit',()=>{ try{ srv.kill(); }catch(e){} });
const API='http://localhost:'+PORT+'/api', BASE='http://localhost:'+PORT+'/werkbonnen.html?api='+encodeURIComponent(API);
async function wachtOpMock(){ for(let i=0;i<50;i++){ try{ const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json','x-code':'admin2026'},body:'{"action":"state"}'}); const j=await r.json(); if(j.bonnen&&j.bonnen.length===0&&j.facturen.length===0) return; throw new Error('mock op poort '+PORT+' heeft al data - test gestopt'); }catch(e){ if(/al data/.test(e.message)) { console.log('FOUT: '+e.message); process.exit(1); } await new Promise(r=>setTimeout(r,200)); } } console.log('FOUT: mock-API start niet (poort '+PORT+')'); process.exit(1); }

async function call(code, body){ const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json','x-code':code},body:JSON.stringify(body)}); return [r.status, await r.json()]; }
const T='bon2026', A='admin2026';
let n=0, fouten=[]; const t=async(naam,fn)=>{ n++; try{ await fn(); }catch(e){ fouten.push(naam+': '+e.message); } };
(async()=>{
  await wachtOpMock();
  await t('onjuiste code -> 401', async()=>{ const [s,j]=await call('fout',{action:'state'}); assert.strictEqual(s,401); assert.strictEqual(j.fout,'onjuiste code'); });
  await t('CORS preflight', async()=>{ const r=await fetch(API,{method:'OPTIONS'}); assert.ok(r.headers.get('access-control-allow-headers').includes('x-code')); });
  await t('onbekende actie -> 400', async()=>{ const [s]=await call(T,{action:'bestaat_niet'}); assert.strictEqual(s,400); });
  await t('state team: rol team, geen logboek', async()=>{ const [s,j]=await call(T,{action:'state'}); assert.strictEqual(s,200); assert.strictEqual(j.rol,'team'); assert.deepStrictEqual(j.logboek,[]); assert.ok(j.tarieven.length>=23); assert.strictEqual(j.projecten.length,2); });
  const st=(await call(A,{action:'state'}))[1]; const p=st.projecten.find(p=>p.code==='26692'); const arb=st.tarieven.find(t=>t.omschrijving==='Arbeid');
  const regel=(aantal,per)=>({categorie:'arbeid',omschrijving:'Arbeid',tarief_id:arb.id,aantal,per,prijs:61.5,eenheid_n:'man',eenheid_per:'uur',eenheid_totaal:'per uur'});
  let bonId;
  await t('bon_save validatie: geen project / datum / lege omschrijving / negatief', async()=>{
    let [s,j]=await call(T,{action:'bon_save',fields:{datum:'2026-08-27'},regels:[]}); assert.strictEqual(s,500); assert.ok(/project/.test(j.fout));
    [s,j]=await call(T,{action:'bon_save',fields:{project_id:p.id,datum:'27-08-2026'},regels:[]}); assert.ok(/datum/.test(j.fout));
    [s,j]=await call(T,{action:'bon_save',fields:{project_id:p.id,datum:'2026-08-27'},regels:[{categorie:'arbeid',omschrijving:'',aantal:1,per:1,prijs:1}]}); assert.ok(/omschrijving leeg/.test(j.fout));
    [s,j]=await call(T,{action:'bon_save',fields:{project_id:p.id,datum:'2026-08-27'},regels:[{categorie:'arbeid',omschrijving:'x',aantal:-1,per:1,prijs:1}]}); assert.ok(/geen geldig getal/.test(j.fout));
    [s,j]=await call(T,{action:'bon_save',fields:{project_id:p.id,datum:'2026-08-27'},regels:[{categorie:'raar',omschrijving:'x',aantal:1,per:1,prijs:1}]}); assert.ok(/categorie/.test(j.fout));
  });
  await t('server weigert halve mannen en halve nachten, accepteert halve uren', async()=>{ let [s,j]=await call(T,{action:'bon_save',fields:{project_id:p.id,datum:'2026-08-27'},regels:[{...regel(2.5,8)}]}); assert.strictEqual(s,500); assert.ok(/heel getal/.test(j.fout)); [s,j]=await call(T,{action:'bon_save',fields:{project_id:p.id,datum:'2026-08-27'},regels:[{categorie:'overnachting',omschrijving:'Overnachtingsvergoeding',aantal:6.5,per:null,prijs:130}]}); assert.ok(/heel getal/.test(j.fout)); [s,j]=await call(T,{action:'bon_save',fields:{project_id:p.id,datum:'2026-08-27'},regels:[{categorie:'transport',omschrijving:'Ophalen materiaal',aantal:5.5,per:null,prijs:130,eenheid_totaal:'per uur'}]}); assert.strictEqual(s,200); await call(T,{action:'bon_delete',id:j.id}); });
  await t('bon_save concept met komma-decimalen wordt server-side nagerekend', async()=>{ const [s,j]=await call(T,{action:'bon_save',wie:'Bas',fields:{project_id:p.id,datum:'2026-08-27',ingevuld_door:'Bas'},regels:[{...regel('3','12,5'),prijs:'61,50',bedrag:1}]}); assert.strictEqual(s,200); bonId=j.id; const st=(await call(T,{action:'state'}))[1]; const r=st.regels.find(r=>r.bon_id===bonId); assert.strictEqual(r.totaal,37.5); assert.strictEqual(r.bedrag,2306.25); assert.strictEqual(st.bonnen.find(b=>b.id===bonId).status,'concept'); });
  await t('indienen zonder regels weigert', async()=>{ const [s,j]=await call(T,{action:'bon_save',id:bonId,fields:{project_id:p.id,datum:'2026-08-27'},regels:[],indienen:true}); assert.strictEqual(s,500); assert.ok(/geen regels/.test(j.fout)); });
  await t('team kan niet beoordelen, admin wel', async()=>{ await call(T,{action:'bon_save',id:bonId,fields:{project_id:p.id,datum:'2026-08-27',afgetekend_door:'Jarno',handtekening_b64:'data:image/png;base64,iVBORw0KGgo='},regels:[regel(3,12.5)],indienen:true}); let [s,j]=await call(T,{action:'bon_beoordeel',id:bonId,besluit:'goedgekeurd'}); assert.strictEqual(s,500); assert.ok(/administratie/.test(j.fout)); [s]=await call(A,{action:'bon_beoordeel',id:bonId,besluit:'afgekeurd',beoordeling:'uren kloppen niet',wie:'Tessa'}); assert.strictEqual(s,200); const b=(await call(A,{action:'state'}))[1].bonnen.find(b=>b.id===bonId); assert.strictEqual(b.status,'afgekeurd'); assert.strictEqual(b.beoordeeld_door,'Tessa'); assert.ok(b.handtekening_pad); });
  await t('team mag ingediende bon niet wijzigen/verwijderen', async()=>{ await call(T,{action:'bon_save',id:bonId,fields:{project_id:p.id,datum:'2026-08-27'},regels:[regel(4,9)],indienen:true}); let [s,j]=await call(T,{action:'bon_save',id:bonId,fields:{project_id:p.id,datum:'2026-08-27'},regels:[regel(1,1)]}); assert.strictEqual(s,500); assert.ok(/administratie/.test(j.fout)); [s,j]=await call(T,{action:'bon_delete',id:bonId}); assert.strictEqual(s,500); const b=(await call(A,{action:'state'}))[1].bonnen.find(b=>b.id===bonId); assert.strictEqual(b.status,'ingediend'); assert.strictEqual(b.beoordeling,''); });
  await t('admin mag ingediende bon wel wijzigen; status blijft ingediend', async()=>{ const [s]=await call(A,{action:'bon_save',id:bonId,fields:{project_id:p.id,datum:'2026-08-27'},regels:[regel(3,12.5),regel(4,9)]}); assert.strictEqual(s,200); const b=(await call(A,{action:'state'}))[1].bonnen.find(b=>b.id===bonId); assert.strictEqual(b.status,'ingediend'); });
  await t('factuur uit niet-goedgekeurde bon weigert', async()=>{ const [s,j]=await call(A,{action:'factuur_maak',project_id:p.id,jaar:2026,week:35,bon_ids:[bonId]}); assert.strictEqual(s,500); assert.ok(/nog niet goedgekeurd/.test(j.fout)); });
  await t('team mag geen factuur/tarief/project/instelling', async()=>{ for(const a of [{action:'factuur_maak'},{action:'tarief_save',fields:{}},{action:'voertuig_save',fields:{}},{action:'medewerker_delete',id:1},{action:'tarief_import',rijen:[{omschrijving:'x',prijs:1}]},{action:'bedrijf_save',fields:{}},{action:'instelling_save'},{action:'tarief_delete',id:1},{action:'factuur_update',id:1,fields:{}},{action:'factuur_delete',id:1}]){ const [s,j]=await call(T,a); assert.strictEqual(s,500,a.action); assert.ok(/administratie/.test(j.fout),a.action); } });
  await call(A,{action:'bon_beoordeel',id:bonId,besluit:'goedgekeurd',wie:'Tessa'});
  let bon2; await t('tweede bon andere week', async()=>{ const [s,j]=await call(T,{action:'bon_save',fields:{project_id:p.id,datum:'2026-09-01'},regels:[regel(2,8)],indienen:true}); bon2=j.id; await call(A,{action:'bon_beoordeel',id:bon2,besluit:'goedgekeurd'}); });
  await t('factuur met bon uit andere week / ander project weigert', async()=>{ let [s,j]=await call(A,{action:'factuur_maak',project_id:p.id,jaar:2026,week:35,bon_ids:[bonId,bon2]}); assert.strictEqual(s,500); assert.ok(/valt niet in week 35/.test(j.fout)); const p2=st.projecten.find(x=>x.code==='26691'); [s,j]=await call(A,{action:'factuur_maak',project_id:p2.id,jaar:2026,week:35,bon_ids:[bonId]}); assert.ok(/ander project/.test(j.fout)); [s,j]=await call(A,{action:'factuur_maak',project_id:p.id,jaar:2026,week:35,bon_ids:[]}); assert.ok(/geen goedgekeurde/.test(j.fout)); });
  let factId;
  await t('factuur aanmaken: nummer, btw, vervaldatum, bonnen gefactureerd, volgnummer opgehoogd', async()=>{ const [s,j]=await call(A,{action:'factuur_maak',wie:'Tessa',project_id:p.id,jaar:2026,week:35,bon_ids:[bonId],datum:'2026-09-05'}); assert.strictEqual(s,200); assert.strictEqual(j.nummer,'2026266'); factId=j.id; const st2=(await call(A,{action:'state'}))[1]; const f=st2.facturen.find(f=>f.id===factId); assert.strictEqual(f.bedrag_excl,4520.25); assert.strictEqual(f.btw_bedrag,949.25); assert.strictEqual(f.bedrag_incl,5469.5); assert.strictEqual(f.vervaldatum,'2026-09-19'); assert.strictEqual(f.status,'concept'); assert.strictEqual(st2.bonnen.find(b=>b.id===bonId).status,'gefactureerd'); assert.strictEqual(st2.instellingen.factuur_volgnummer,'267'); });
  await t('dubbel factuurnummer weigert', async()=>{ const [s,j]=await call(A,{action:'factuur_maak',project_id:p.id,jaar:2026,week:36,bon_ids:[bon2],nummer:'2026266'}); assert.strictEqual(s,500); assert.ok(/bestaat al/.test(j.fout)); const b=(await call(A,{action:'state'}))[1].bonnen.find(b=>b.id===bon2); assert.strictEqual(b.status,'goedgekeurd','bon mag niet gefactureerd raken bij mislukte factuur'); });
  await t('gefactureerde bon: niet wijzigen/beoordelen/verwijderen', async()=>{ let [s,j]=await call(A,{action:'bon_save',id:bonId,fields:{project_id:p.id,datum:'2026-08-27'},regels:[regel(1,1)]}); assert.ok(/factuur/.test(j.fout)); [s,j]=await call(A,{action:'bon_beoordeel',id:bonId,besluit:'afgekeurd'}); assert.ok(/factuur/.test(j.fout)); [s,j]=await call(A,{action:'bon_delete',id:bonId}); assert.ok(/factuur/.test(j.fout)); });
  await t('factuur_update: btw herberekend, status, ongeldige status/datum', async()=>{ let [s]=await call(A,{action:'factuur_update',id:factId,fields:{btw_pct:'9',nummer:'2026266A'}}); assert.strictEqual(s,200); let f=(await call(A,{action:'state'}))[1].facturen.find(f=>f.id===factId); assert.strictEqual(f.btw_bedrag,406.82); assert.strictEqual(f.bedrag_incl,4927.07); assert.strictEqual(f.nummer,'2026266A'); let j; [s,j]=await call(A,{action:'factuur_update',id:factId,fields:{status:'betaald'}}); assert.ok(/status/.test(j.fout)); [s,j]=await call(A,{action:'factuur_update',id:factId,fields:{datum:'5-9-2026'}}); assert.ok(/datum/.test(j.fout)); [s]=await call(A,{action:'factuur_update',id:factId,fields:{status:'definitief'}}); assert.strictEqual(s,200); });
  await t('definitieve factuur kan niet vervallen; concept wel en bonnen terug naar goedgekeurd', async()=>{ let [s,j]=await call(A,{action:'factuur_delete',id:factId}); assert.strictEqual(s,500); assert.ok(/concept/.test(j.fout)); await call(A,{action:'factuur_update',id:factId,fields:{status:'concept'}}); [s]=await call(A,{action:'factuur_delete',id:factId}); assert.strictEqual(s,200); const st3=(await call(A,{action:'state'}))[1]; assert.ok(!st3.facturen.some(f=>f.id===factId)); const b=st3.bonnen.find(b=>b.id===bonId); assert.strictEqual(b.status,'goedgekeurd'); assert.strictEqual(b.factuur_id,null); });
  await t('tarief: opslaan, prijs met komma, deactiveren', async()=>{ let [s]=await call(A,{action:'tarief_save',fields:{categorie:'materieel',omschrijving:'Gebruik kraan',eenheid_totaal:'per dag',prijs:'400,00',dagtype:'alle',sort:38}}); assert.strictEqual(s,200); let st4=(await call(A,{action:'state'}))[1]; const k=st4.tarieven.find(t=>t.omschrijving==='Gebruik kraan'); assert.strictEqual(k.prijs,400); [s]=await call(A,{action:'tarief_delete',id:k.id}); st4=(await call(A,{action:'state'}))[1]; assert.strictEqual(st4.tarieven.find(t=>t.id===k.id).actief,false); const [s2,j2]=await call(A,{action:'tarief_save',fields:{categorie:'x',omschrijving:'y'}}); assert.ok(/categorie/.test(j2.fout)); });
  await t('instellingen opslaan', async()=>{ await call(A,{action:'instelling_save',instellingen:{factuur_prefix:'F2026-',factuur_volgnummer:'1',betaaltermijn_dagen:'30'}}); const i=(await call(A,{action:'state'}))[1].instellingen; assert.strictEqual(i.factuur_prefix,'F2026-'); assert.strictEqual(i.betaaltermijn_dagen,'30'); const [s,j]=await call(A,{action:'factuur_maak',project_id:p.id,jaar:2026,week:36,bon_ids:[bon2],datum:'2026-09-05'}); assert.strictEqual(j.nummer,'F2026-001'); const f=(await call(A,{action:'state'}))[1].facturen.find(f=>f.id===j.id); assert.strictEqual(f.vervaldatum,'2026-10-05'); });
  await t('foto-upload: max 10, paden bewaard, verwijderen via foto_paden', async()=>{ const [s,j]=await call(T,{action:'bon_save',fields:{project_id:p.id,datum:'2026-09-02',fotos_b64:Array(11).fill('data:image/jpeg;base64,/9j/')},regels:[regel(1,1)]}); assert.ok(/maximaal 10/.test(j.fout)); const [s2,j2]=await call(T,{action:'bon_save',fields:{project_id:p.id,datum:'2026-09-02',fotos_b64:['data:image/jpeg;base64,/9j/','data:image/jpeg;base64,/9j/']},regels:[regel(1,1)]}); let b=(await call(T,{action:'state'}))[1].bonnen.find(b=>b.id===j2.id); assert.strictEqual(b.foto_paden.length,2); await call(T,{action:'bon_save',id:j2.id,fields:{project_id:p.id,datum:'2026-09-02',foto_paden:[b.foto_paden[1]],fotos_b64:['data:image/jpeg;base64,/9j/']},regels:[regel(1,1)]}); b=(await call(T,{action:'state'}))[1].bonnen.find(b=>b.id===j2.id); assert.strictEqual(b.foto_paden.length,2); });
  await t('logboek vult zich (admin)', async()=>{ await call(A,{action:'instelling_save',instellingen:{},log:'test'}); const l=(await call(A,{action:'state'}))[1].logboek; assert.ok(l.length>0); });
  await t('project_save: team mag project aanmaken (wizard), code+naam verplicht, dubbele code geweigerd, id terug', async()=>{ let [s,j]=await call(T,{action:'project_save',fields:{}}); assert.strictEqual(s,500); assert.ok(/projectcode/.test(j.fout)); [s,j]=await call(T,{action:'project_save',fields:{code:'26691',naam:'Dubbel'}}); assert.ok(/bestaat al/.test(j.fout)); [s,j]=await call(T,{action:'project_save',wie:'Piet',fields:{code:'26699',naam:'Test',adres:'Weg 1',postcode_plaats:'1234 AB Ens',afstand_km:'61,5',opdrachtgever_id:2,aannemer_id:1}}); assert.strictEqual(s,200,JSON.stringify(j)); assert.ok(j.id); const st=(await call(T,{action:'state'}))[1]; const p=st.projecten.find(p=>p.id===j.id); assert.strictEqual(p.afstand_km,61.5); assert.strictEqual(p.aangemaakt_door,'Piet'); await call(A,{action:'project_save',id:j.id,fields:{actief:false}}); });
  await t('projecttarief_save: prijzen per project (upsert), onbekend tarief geweigerd', async()=>{ const st=(await call(T,{action:'state'}))[1]; const p=st.projecten.find(p=>p.code==='26699'); const t=st.tarieven.find(t=>t.omschrijving==='Arbeid'); let [s,j]=await call(T,{action:'projecttarief_save',project_id:p.id,prijzen:[{tarief_id:t.id,prijs:'62,25'}]}); assert.strictEqual(s,200,JSON.stringify(j)); [s,j]=await call(T,{action:'projecttarief_save',project_id:p.id,prijzen:[{tarief_id:t.id,prijs:63}]}); assert.strictEqual(s,200); const st2=(await call(T,{action:'state'}))[1]; const pt=st2.projecttarieven.filter(x=>x.project_id===p.id); assert.strictEqual(pt.length,1); assert.strictEqual(pt[0].prijs,63); [s,j]=await call(T,{action:'projecttarief_save',project_id:p.id,prijzen:[{tarief_id:99999,prijs:1}]}); assert.strictEqual(s,500); [s,j]=await call(T,{action:'projecttarief_save',project_id:99999,prijzen:[]}); assert.strictEqual(s,500); });
  await t('medewerker_save: team voegt naam toe (te controleren, dubbel = zelfde id), team/admin corrigeren en bevestigen; voertuig_save alleen admin', async()=>{ let [s,j]=await call(T,{action:'medewerker_save',wie:'Piet',fields:{naam:'Test Persoon'}}); assert.strictEqual(s,200); const id=j.id; let st=(await call(A,{action:'state'}))[1]; let m=st.medewerkers.find(m=>m.id===id); assert.strictEqual(m.gecontroleerd,false); assert.strictEqual(m.bron,'werkvloer'); assert.strictEqual(m.aangemaakt_door,'Piet'); [s,j]=await call(T,{action:'medewerker_save',fields:{naam:'test persoon'}}); assert.strictEqual(j.id,id); assert.ok(j.bestaand); [s,j]=await call(T,{action:'medewerker_save',fields:{naam:'  '}}); assert.strictEqual(s,500); [s,j]=await call(T,{action:'medewerker_save',id,fields:{naam:'Nick Mesken'}}); assert.strictEqual(s,500); assert.ok(/samenvoegen/.test(j.fout)); [s]=await call(T,{action:'medewerker_save',id,fields:{naam:'Test Persoon-Jansen',gecontroleerd:true}}); assert.strictEqual(s,200); st=(await call(A,{action:'state'}))[1]; m=st.medewerkers.find(m=>m.id===id); assert.strictEqual(m.gecontroleerd,true); assert.strictEqual(m.naam,'Test Persoon-Jansen'); [s]=await call(A,{action:'medewerker_save',id,fields:{functie:'monteur',sort:5}}); assert.strictEqual(s,200); [s]=await call(A,{action:'medewerker_delete',id}); assert.strictEqual(s,200); st=(await call(A,{action:'state'}))[1]; assert.strictEqual(st.medewerkers.find(m=>m.id===id).actief,false);
    [s,j]=await call(A,{action:'medewerker_save',fields:{naam:'Kantoor Naam'}}); assert.strictEqual((await call(A,{action:'state'}))[1].medewerkers.find(m=>m.id===j.id).gecontroleerd,true); await call(A,{action:'medewerker_delete',id:j.id});
    [s,j]=await call(A,{action:'voertuig_save',fields:{naam:'Bus 9',soort:'auto'}}); assert.strictEqual(s,200); [s,j]=await call(A,{action:'voertuig_save',fields:{naam:'Bus 9',soort:'auto'}}); assert.ok(/bestaat al/.test(j.fout)); [s,j]=await call(A,{action:'voertuig_save',fields:{naam:'Ding',soort:'fiets'}}); assert.ok(/soort/.test(j.fout)); const v=(await call(A,{action:'state'}))[1].voertuigen.find(v=>v.naam==='Bus 9'); [s]=await call(A,{action:'voertuig_delete',id:v.id}); assert.strictEqual(s,200); });
  await t('medewerker_merge: ploegen op bonnen en regel-namen omgezet, oude naam vervalt', async()=>{ const st=(await call(T,{action:'state'}))[1]; const goed=st.medewerkers.find(m=>m.naam==='Nick Mesken').id; const fout=(await call(T,{action:'medewerker_save',wie:'Piet',fields:{naam:'Nick Mesk'}}))[1].id; const t=st.tarieven.find(t=>t.omschrijving==='Arbeid');
    const [s0,b0]=await call(T,{action:'bon_save',fields:{project_id:st.projecten[0].id,datum:'2026-09-09',invoer:{shifts:[{aantal_man:2,start:'06:00',eind:'16:00',pauze:'',leden:[fout,goed],overnachting:false,nachten:''}],voertuigen:[]}},regels:[{categorie:'arbeid',omschrijving:'Arbeid',tarief_id:t.id,aantal:2,per:9.5,prijs:61.5,eenheid_n:'man',eenheid_per:'uur',eenheid_totaal:'per uur',namen:'Nick Mesk, Nick Mesken',bron:'shift'}]}); assert.strictEqual(s0,200,JSON.stringify(b0));
    let [s,j]=await call(T,{action:'medewerker_merge',id:fout,in_id:fout}); assert.strictEqual(s,500); [s,j]=await call(T,{action:'medewerker_merge',id:fout,in_id:goed}); assert.strictEqual(s,200,JSON.stringify(j)); assert.strictEqual(j.bonnen,1); const st2=(await call(A,{action:'state'}))[1]; const b=st2.bonnen.find(b=>b.id===b0.id); assert.deepStrictEqual(b.invoer.shifts[0].leden,[goed]); assert.strictEqual(st2.regels.find(r=>r.bon_id===b.id).namen,'Nick Mesken, Nick Mesken'); assert.strictEqual(st2.medewerkers.find(m=>m.id===fout).actief,false); await call(A,{action:'bon_delete',id:b.id}); });
  await t('bon_save: invoer (shifts/voertuigen) wordt bewaard, bron per regel; afrondingsregels', async()=>{ const st=(await call(T,{action:'state'}))[1]; const p=st.projecten[0]; const t=st.tarieven.find(t=>t.omschrijving==='Arbeid'); const km=st.tarieven.find(t=>t.categorie==='km'); const inv={shifts:[{aantal_man:3,start:'06:30',eind:'19:30',pauze:'',leden:[1],overnachting:true,nachten:''}],voertuigen:[{voertuig_id:1,naam:'Bus 1',soort:'auto',gebracht:true,km:54.5,dagdeel:1}]};
    const mk=(o)=>Object.assign({categorie:'arbeid',omschrijving:'Arbeid',tarief_id:t.id,aantal:3,per:12.5,prijs:61.5,eenheid_n:'man',eenheid_per:'uur',eenheid_totaal:'per uur',bron:'shift'},o);
    let [s,j]=await call(T,{action:'bon_save',fields:{project_id:p.id,datum:'2026-09-08',invoer:inv},regels:[mk({}),mk({categorie:'km',omschrijving:'Kilometervergoeding',tarief_id:km.id,aantal:1,per:54.5,prijs:0.7,eenheid_n:"auto's",eenheid_per:'km.',eenheid_totaal:'per km.',bron:'voertuig'}),mk({categorie:'materieel',omschrijving:'Gebruik hoogwerker incl. brandstof',aantal:1,per:0.75,prijs:300,eenheid_n:'stuks',eenheid_per:'dag',eenheid_totaal:'per dag',bron:'voertuig'}),mk({categorie:'transport',omschrijving:'Transport materieel (gebracht)',aantal:60.5,per:null,prijs:1.5,eenheid_n:'',eenheid_per:'',eenheid_totaal:'per km',bron:'extra'})]}); assert.strictEqual(s,200,JSON.stringify(j));
    const st2=(await call(A,{action:'state'}))[1]; const b=st2.bonnen.find(b=>b.id===j.id); assert.deepStrictEqual(JSON.stringify(b.invoer),JSON.stringify(inv)); const rs=st2.regels.filter(r=>r.bon_id===b.id); assert.deepStrictEqual(rs.map(r=>r.bron),['shift','voertuig','voertuig','extra']); assert.strictEqual(rs[2].bedrag,225); assert.strictEqual(rs[3].bedrag,90.75);
    for(const bad of [mk({per:12.25}),mk({categorie:'km',omschrijving:'K',aantal:1,per:54.3,eenheid_per:'km.'}),mk({categorie:'materieel',omschrijving:'M',aantal:1,per:0.6,eenheid_per:'dag'}),mk({categorie:'transport',omschrijving:'T',aantal:5.25,per:null}),mk({categorie:'overnachting',omschrijving:'O',aantal:2.5,per:null})]){ const [s2,j2]=await call(T,{action:'bon_save',fields:{project_id:p.id,datum:'2026-09-08'},regels:[bad]}); assert.strictEqual(s2,500,JSON.stringify(bad)); assert.ok(/stappen|heel getal|halve uren/.test(j2.fout),j2.fout); }
    [s,j]=await call(T,{action:'bon_save',fields:{project_id:p.id,datum:'2026-09-08',invoer:[1,2]},regels:[]}); assert.strictEqual(s,500); assert.ok(/invoer/.test(j.fout)); await call(A,{action:'bon_delete',id:b.id}); });
  await t('tarief_import: nieuw + bijwerken, categorie, alleen admin', async()=>{ let [s,j]=await call(A,{action:'tarief_import',rijen:[{omschrijving:'Bout M6x50 + moer',prijs:'0,18',eenheid_totaal:'per stuk'},{omschrijving:'siliconen kit',prijs:3.6},{omschrijving:'Transport kraan',prijs:120,eenheid_totaal:'per uur',categorie:'transport'},{omschrijving:'',prijs:1}]}); assert.strictEqual(s,200,JSON.stringify(j)); assert.strictEqual(j.nieuw,2); assert.strictEqual(j.bijgewerkt,1); const st=(await call(A,{action:'state'}))[1]; assert.strictEqual(st.tarieven.find(t=>t.omschrijving==='Siliconen kit').prijs,3.6); assert.strictEqual(st.tarieven.find(t=>t.omschrijving==='Transport kraan').categorie,'transport'); [s,j]=await call(A,{action:'tarief_import',rijen:[]}); assert.strictEqual(s,500); [s,j]=await call(A,{action:'tarief_import',rijen:[{omschrijving:'X',prijs:'abc'}]}); assert.strictEqual(s,500); });
  await t('testdata wissen: alleen admin, alleen met WISSEN, stamdata blijft', async()=>{ let [s,j]=await call(T,{action:'testdata_wissen',bevestiging:'WISSEN'}); assert.ok(/administratie/.test(j.fout)); [s,j]=await call(A,{action:'testdata_wissen',bevestiging:'ja'}); assert.ok(/bevestiging/.test(j.fout)); [s]=await call(A,{action:'testdata_wissen',bevestiging:'WISSEN',log:'gewist'}); assert.strictEqual(s,200); const st5=(await call(A,{action:'state'}))[1]; assert.strictEqual(st5.bonnen.length,0); assert.strictEqual(st5.regels.length,0); assert.strictEqual(st5.facturen.length,0); assert.ok(st5.tarieven.length>20); assert.strictEqual(st5.projecten.length,3); assert.ok(st5.medewerkers.length>5&&st5.voertuigen.length>5); });
  console.log('api-tests:', n, 'uitgevoerd,', fouten.length, 'fouten'); for(const x of fouten) console.log('  FOUT', x); process.exit(fouten.length?1:0);
})();
