// API-tests via HTTP tegen de mock. Start: node tools/werkbonnen-api.js
// API-tests via HTTP tegen de mock (zelfde regels als de edge function), zonder browser.
 const assert=require('assert');
const { spawn } = require('child_process');
const PORT=18000+Math.floor(Math.random()*2000);
const srv=spawn(process.execPath,[require('path').join(__dirname,'werkbonnen-mock.js')],{stdio:'ignore',env:{...process.env,WB_PORT:String(PORT)}}); process.on('exit',()=>{ try{ srv.kill(); }catch(e){} });
const API='http://localhost:'+PORT+'/api', BASE='http://localhost:'+PORT+'/werkbonnen.html?api='+encodeURIComponent(API);
async function wachtOpMock(){ for(let i=0;i<50;i++){ try{ const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json','x-code':'admin2026'},body:'{"action":"state"}'}); const j=await r.json(); if(j.bonnen&&j.bonnen.length===0&&j.facturen.length===0) return; throw new Error('mock op poort '+PORT+' heeft al data - test gestopt'); }catch(e){ if(/al data/.test(e.message)) { console.log('FOUT: '+e.message); process.exit(1); } await new Promise(r=>setTimeout(r,200)); } } console.log('FOUT: mock-API start niet (poort '+PORT+')'); process.exit(1); }

async function call(code, body){ const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json','x-code':code},body:JSON.stringify(body)}); return [r.status, await r.json()]; }
const T='bon2026', A='admin2026';
let n=0, fouten=[]; const t=async(naam,fn)=>{ n++; try{ await fn(); }catch(e){ fouten.push(naam+': '+e.message); } };
(async()=>{
  await wachtOpMock();
  await t('onjuiste code -> 401', async()=>{ const [s,j]=await call('fout',{action:'state'}); assert.strictEqual(s,401); assert.strictEqual(j.fout,'onjuiste code'); });
  await t('CORS preflight', async()=>{ const r=await fetch(API,{method:'OPTIONS'}); assert.ok(r.headers.get('access-control-allow-headers').includes('x-code')); });
  await t('onbekende actie -> 400', async()=>{ const [s]=await call(T,{action:'bestaat_niet'}); assert.strictEqual(s,400); });
  await t('state team: rol team, geen logboek', async()=>{ const [s,j]=await call(T,{action:'state'}); assert.strictEqual(s,200); assert.strictEqual(j.rol,'team'); assert.deepStrictEqual(j.logboek,[]); assert.ok(j.tarieven.length>=23); assert.strictEqual(j.projecten.length,2); });
  const st=(await call(A,{action:'state'}))[1]; const p=st.projecten.find(p=>p.code==='26692'); const arb=st.tarieven.find(t=>t.omschrijving==='Arbeid');
  const regel=(aantal,per)=>({categorie:'arbeid',omschrijving:'Arbeid',tarief_id:arb.id,aantal,per,prijs:61.5,eenheid_n:'man',eenheid_per:'uur',eenheid_totaal:'per uur'});
  let bonId;
  await t('bon_save validatie: geen project / datum / lege omschrijving / negatief', async()=>{
    let [s,j]=await call(T,{action:'bon_save',fields:{datum:'2026-08-27'},regels:[]}); assert.strictEqual(s,500); assert.ok(/project/.test(j.fout));
    [s,j]=await call(T,{action:'bon_save',fields:{project_id:p.id,datum:'27-08-2026'},regels:[]}); assert.ok(/datum/.test(j.fout));
    [s,j]=await call(T,{action:'bon_save',fields:{project_id:p.id,datum:'2026-08-27'},regels:[{categorie:'arbeid',omschrijving:'',aantal:1,per:1,prijs:1}]}); assert.ok(/omschrijving leeg/.test(j.fout));
    [s,j]=await call(T,{action:'bon_save',fields:{project_id:p.id,datum:'2026-08-27'},regels:[{categorie:'arbeid',omschrijving:'x',aantal:-1,per:1,prijs:1}]}); assert.ok(/geen geldig getal/.test(j.fout));
    [s,j]=await call(T,{action:'bon_save',fields:{project_id:p.id,datum:'2026-08-27'},regels:[{categorie:'raar',omschrijving:'x',aantal:1,per:1,prijs:1}]}); assert.ok(/categorie/.test(j.fout));
  });
  await t('bon_save concept met komma-decimalen wordt server-side nagerekend', async()=>{ const [s,j]=await call(T,{action:'bon_save',wie:'Bas',fields:{project_id:p.id,datum:'2026-08-27',ingevuld_door:'Bas'},regels:[{...regel('3','12,5'),prijs:'61,50',bedrag:1}]}); assert.strictEqual(s,200); bonId=j.id; const st=(await call(T,{action:'state'}))[1]; const r=st.regels.find(r=>r.bon_id===bonId); assert.strictEqual(r.totaal,37.5); assert.strictEqual(r.bedrag,2306.25); assert.strictEqual(st.bonnen.find(b=>b.id===bonId).status,'concept'); });
  await t('indienen zonder regels weigert', async()=>{ const [s,j]=await call(T,{action:'bon_save',id:bonId,fields:{project_id:p.id,datum:'2026-08-27'},regels:[],indienen:true}); assert.strictEqual(s,500); assert.ok(/geen regels/.test(j.fout)); });
  await t('team kan niet beoordelen, admin wel', async()=>{ await call(T,{action:'bon_save',id:bonId,fields:{project_id:p.id,datum:'2026-08-27',afgetekend_door:'Jarno',handtekening_b64:'data:image/png;base64,iVBORw0KGgo='},regels:[regel(3,12.5)],indienen:true}); let [s,j]=await call(T,{action:'bon_beoordeel',id:bonId,besluit:'goedgekeurd'}); assert.strictEqual(s,500); assert.ok(/administratie/.test(j.fout)); [s]=await call(A,{action:'bon_beoordeel',id:bonId,besluit:'afgekeurd',beoordeling:'uren kloppen niet',wie:'Tessa'}); assert.strictEqual(s,200); const b=(await call(A,{action:'state'}))[1].bonnen.find(b=>b.id===bonId); assert.strictEqual(b.status,'afgekeurd'); assert.strictEqual(b.beoordeeld_door,'Tessa'); assert.ok(b.handtekening_pad); });
  await t('team mag ingediende bon niet wijzigen/verwijderen', async()=>{ await call(T,{action:'bon_save',id:bonId,fields:{project_id:p.id,datum:'2026-08-27'},regels:[regel(4,9)],indienen:true}); let [s,j]=await call(T,{action:'bon_save',id:bonId,fields:{project_id:p.id,datum:'2026-08-27'},regels:[regel(1,1)]}); assert.strictEqual(s,500); assert.ok(/administratie/.test(j.fout)); [s,j]=await call(T,{action:'bon_delete',id:bonId}); assert.strictEqual(s,500); const b=(await call(A,{action:'state'}))[1].bonnen.find(b=>b.id===bonId); assert.strictEqual(b.status,'ingediend'); assert.strictEqual(b.beoordeling,''); });
  await t('admin mag ingediende bon wel wijzigen; status blijft ingediend', async()=>{ const [s]=await call(A,{action:'bon_save',id:bonId,fields:{project_id:p.id,datum:'2026-08-27'},regels:[regel(3,12.5),regel(4,9)]}); assert.strictEqual(s,200); const b=(await call(A,{action:'state'}))[1].bonnen.find(b=>b.id===bonId); assert.strictEqual(b.status,'ingediend'); });
  await t('factuur uit niet-goedgekeurde bon weigert', async()=>{ const [s,j]=await call(A,{action:'factuur_maak',project_id:p.id,jaar:2026,week:35,bon_ids:[bonId]}); assert.strictEqual(s,500); assert.ok(/nog niet goedgekeurd/.test(j.fout)); });
  await t('team mag geen factuur/tarief/project/instelling', async()=>{ for(const a of [{action:'factuur_maak'},{action:'tarief_save',fields:{}},{action:'project_save',fields:{}},{action:'bedrijf_save',fields:{}},{action:'instelling_save'},{action:'tarief_delete',id:1},{action:'factuur_update',id:1,fields:{}},{action:'factuur_delete',id:1}]){ const [s,j]=await call(T,a); assert.strictEqual(s,500,a.action); assert.ok(/administratie/.test(j.fout),a.action); } });
  await call(A,{action:'bon_beoordeel',id:bonId,besluit:'goedgekeurd',wie:'Tessa'});
  let bon2; await t('tweede bon andere week', async()=>{ const [s,j]=await call(T,{action:'bon_save',fields:{project_id:p.id,datum:'2026-09-01'},regels:[regel(2,8)],indienen:true}); bon2=j.id; await call(A,{action:'bon_beoordeel',id:bon2,besluit:'goedgekeurd'}); });
  await t('factuur met bon uit andere week / ander project weigert', async()=>{ let [s,j]=await call(A,{action:'factuur_maak',project_id:p.id,jaar:2026,week:35,bon_ids:[bonId,bon2]}); assert.strictEqual(s,500); assert.ok(/valt niet in week 35/.test(j.fout)); const p2=st.projecten.find(x=>x.code==='26691'); [s,j]=await call(A,{action:'factuur_maak',project_id:p2.id,jaar:2026,week:35,bon_ids:[bonId]}); assert.ok(/ander project/.test(j.fout)); [s,j]=await call(A,{action:'factuur_maak',project_id:p.id,jaar:2026,week:35,bon_ids:[]}); assert.ok(/geen goedgekeurde/.test(j.fout)); });
  let factId;
  await t('factuur aanmaken: nummer, btw, vervaldatum, bonnen gefactureerd, volgnummer opgehoogd', async()=>{ const [s,j]=await call(A,{action:'factuur_maak',wie:'Tessa',project_id:p.id,jaar:2026,week:35,bon_ids:[bonId],datum:'2026-09-05'}); assert.strictEqual(s,200); assert.strictEqual(j.nummer,'2026266'); factId=j.id; const st2=(await call(A,{action:'state'}))[1]; const f=st2.facturen.find(f=>f.id===factId); assert.strictEqual(f.bedrag_excl,4520.25); assert.strictEqual(f.btw_bedrag,949.25); assert.strictEqual(f.bedrag_incl,5469.5); assert.strictEqual(f.vervaldatum,'2026-09-19'); assert.strictEqual(f.status,'concept'); assert.strictEqual(st2.bonnen.find(b=>b.id===bonId).status,'gefactureerd'); assert.strictEqual(st2.instellingen.factuur_volgnummer,'267'); });
  await t('dubbel factuurnummer weigert', async()=>{ const [s,j]=await call(A,{action:'factuur_maak',project_id:p.id,jaar:2026,week:36,bon_ids:[bon2],nummer:'2026266'}); assert.strictEqual(s,500); assert.ok(/bestaat al/.test(j.fout)); const b=(await call(A,{action:'state'}))[1].bonnen.find(b=>b.id===bon2); assert.strictEqual(b.status,'goedgekeurd','bon mag niet gefactureerd raken bij mislukte factuur'); });
  await t('gefactureerde bon: niet wijzigen/beoordelen/verwijderen', async()=>{ let [s,j]=await call(A,{action:'bon_save',id:bonId,fields:{project_id:p.id,datum:'2026-08-27'},regels:[regel(1,1)]}); assert.ok(/factuur/.test(j.fout)); [s,j]=await call(A,{action:'bon_beoordeel',id:bonId,besluit:'afgekeurd'}); assert.ok(/factuur/.test(j.fout)); [s,j]=await call(A,{action:'bon_delete',id:bonId}); assert.ok(/factuur/.test(j.fout)); });
  await t('factuur_update: btw herberekend, status, ongeldige status/datum', async()=>{ let [s]=await call(A,{action:'factuur_update',id:factId,fields:{btw_pct:'9',nummer:'2026266A'}}); assert.strictEqual(s,200); let f=(await call(A,{action:'state'}))[1].facturen.find(f=>f.id===factId); assert.strictEqual(f.btw_bedrag,406.82); assert.strictEqual(f.bedrag_incl,4927.07); assert.strictEqual(f.nummer,'2026266A'); let j; [s,j]=await call(A,{action:'factuur_update',id:factId,fields:{status:'betaald'}}); assert.ok(/status/.test(j.fout)); [s,j]=await call(A,{action:'factuur_update',id:factId,fields:{datum:'5-9-2026'}}); assert.ok(/datum/.test(j.fout)); [s]=await call(A,{action:'factuur_update',id:factId,fields:{status:'definitief'}}); assert.strictEqual(s,200); });
  await t('definitieve factuur kan niet vervallen; concept wel en bonnen terug naar goedgekeurd', async()=>{ let [s,j]=await call(A,{action:'factuur_delete',id:factId}); assert.strictEqual(s,500); assert.ok(/concept/.test(j.fout)); await call(A,{action:'factuur_update',id:factId,fields:{status:'concept'}}); [s]=await call(A,{action:'factuur_delete',id:factId}); assert.strictEqual(s,200); const st3=(await call(A,{action:'state'}))[1]; assert.ok(!st3.facturen.some(f=>f.id===factId)); const b=st3.bonnen.find(b=>b.id===bonId); assert.strictEqual(b.status,'goedgekeurd'); assert.strictEqual(b.factuur_id,null); });
  await t('tarief: opslaan, prijs met komma, deactiveren', async()=>{ let [s]=await call(A,{action:'tarief_save',fields:{categorie:'materieel',omschrijving:'Gebruik kraan',eenheid_totaal:'per dag',prijs:'400,00',dagtype:'alle',sort:38}}); assert.strictEqual(s,200); let st4=(await call(A,{action:'state'}))[1]; const k=st4.tarieven.find(t=>t.omschrijving==='Gebruik kraan'); assert.strictEqual(k.prijs,400); [s]=await call(A,{action:'tarief_delete',id:k.id}); st4=(await call(A,{action:'state'}))[1]; assert.strictEqual(st4.tarieven.find(t=>t.id===k.id).actief,false); const [s2,j2]=await call(A,{action:'tarief_save',fields:{categorie:'x',omschrijving:'y'}}); assert.ok(/categorie/.test(j2.fout)); });
  await t('instellingen opslaan', async()=>{ await call(A,{action:'instelling_save',instellingen:{factuur_prefix:'F2026-',factuur_volgnummer:'1',betaaltermijn_dagen:'30'}}); const i=(await call(A,{action:'state'}))[1].instellingen; assert.strictEqual(i.factuur_prefix,'F2026-'); assert.strictEqual(i.betaaltermijn_dagen,'30'); const [s,j]=await call(A,{action:'factuur_maak',project_id:p.id,jaar:2026,week:36,bon_ids:[bon2],datum:'2026-09-05'}); assert.strictEqual(j.nummer,'F2026-001'); const f=(await call(A,{action:'state'}))[1].facturen.find(f=>f.id===j.id); assert.strictEqual(f.vervaldatum,'2026-10-05'); });
  await t('foto-upload: max 10, paden bewaard, verwijderen via foto_paden', async()=>{ const [s,j]=await call(T,{action:'bon_save',fields:{project_id:p.id,datum:'2026-09-02',fotos_b64:Array(11).fill('data:image/jpeg;base64,/9j/')},regels:[regel(1,1)]}); assert.ok(/maximaal 10/.test(j.fout)); const [s2,j2]=await call(T,{action:'bon_save',fields:{project_id:p.id,datum:'2026-09-02',fotos_b64:['data:image/jpeg;base64,/9j/','data:image/jpeg;base64,/9j/']},regels:[regel(1,1)]}); let b=(await call(T,{action:'state'}))[1].bonnen.find(b=>b.id===j2.id); assert.strictEqual(b.foto_paden.length,2); await call(T,{action:'bon_save',id:j2.id,fields:{project_id:p.id,datum:'2026-09-02',foto_paden:[b.foto_paden[1]],fotos_b64:['data:image/jpeg;base64,/9j/']},regels:[regel(1,1)]}); b=(await call(T,{action:'state'}))[1].bonnen.find(b=>b.id===j2.id); assert.strictEqual(b.foto_paden.length,2); });
  await t('logboek vult zich (admin)', async()=>{ await call(A,{action:'instelling_save',instellingen:{},log:'test'}); const l=(await call(A,{action:'state'}))[1].logboek; assert.ok(l.length>0); });
  console.log('api-tests:', n, 'uitgevoerd,', fouten.length, 'fouten'); for(const x of fouten) console.log('  FOUT', x); process.exit(fouten.length?1:0);
})();
